### ISSUE TITLE
CTMS-151 Rotate Tokens

### ISSUE THREAD

**Issue by bsieber-mozilla** [mozilla/syseng-pod#2]
Tracking for https://mozilla-hub.atlassian.net/browse/CTMS-151
All details will be in the Jira Issue

----
Written Process Exists prior to issue? 
- NO

Process extracted from notes of prior incident:
https://docs.google.com/document/d/1T7vAHrUSTU0yiy3YcxDqh5pOJ2omNza6oX8ViGwy7AA/edit#heading=h.142ax9meksel

Since the written process now exists; and since these notes were generated by Graham originally, this feels like a "solid"/proven process that doesn't require a team-decision.

**Comment by bsieber-mozilla** [comment]
Moved to blocked state--ball is in motion; but requires external stakeholders and SRE coordination and time alignment. 
SRE Support request: https://mozilla-hub.atlassian.net/browse/SE-3496

**Comment by grahamalama** [comment]
The tokens were force synced to Acoustic on Friday afternoon, so we can consider this ticket complete.
